SELECT 'kecamatan' q, nama FROM kecamatan ORDER BY id;
SELECT 'lahan_penggunaan.kategori' q, DISTINCT_DUMMY FROM (SELECT DISTINCT kategori AS DISTINCT_DUMMY FROM lahan_penggunaan) x;
SELECT 'pasar.jenis' q, jenis FROM pasar GROUP BY jenis;
SELECT 'inflasi.wilayah' q, wilayah FROM inflasi GROUP BY wilayah;
SELECT 'ternak_populasi' q, CONCAT(kelompok,'=',jenis) FROM ternak_populasi GROUP BY kelompok, jenis;
SELECT 'ternak_flow' q, CONCAT(arah,'=',jenis) FROM ternak_flow GROUP BY arah, jenis;
SELECT 'ternak_pemotongan luar_rph' q, jenis FROM ternak_pemotongan WHERE lokasi='luar_rph' GROUP BY jenis;
SELECT 'ternak_daging unggas' q, jenis FROM ternak_daging WHERE kelompok='unggas' GROUP BY jenis;
SELECT 'ikan_tangkap.jenis_alat' q, jenis_alat FROM ikan_tangkap GROUP BY jenis_alat;
SELECT 'ikan_budidaya.jenis_budidaya' q, jenis_budidaya FROM ikan_budidaya GROUP BY jenis_budidaya;
SELECT 'ikan_pemeliharaan.tempat' q, tempat FROM ikan_pemeliharaan GROUP BY tempat;
SELECT 'horti_produksi sayuran' q, komoditas FROM horti_produksi WHERE kelompok='sayuran' GROUP BY komoditas;
SELECT 'horti_produksi buah' q, komoditas FROM horti_produksi WHERE kelompok='buah_tahunan' GROUP BY komoditas;
SELECT 'horti_luas sayuran' q, komoditas FROM horti_luas WHERE kelompok='sayuran' GROUP BY komoditas;
SELECT 'horti_kab buah_sayuran_tahunan' q, komoditas FROM horti_produksi_kabupaten WHERE kelompok='buah_sayuran_tahunan' GROUP BY komoditas;
SELECT 'palawija' q, komoditas FROM palawija_produksi GROUP BY komoditas;
SELECT 'perkebunan_areal' q, tanaman FROM perkebunan_areal GROUP BY tanaman;
SELECT 'perkebunan_produksi' q, tanaman FROM perkebunan_produksi GROUP BY tanaman;
SELECT 'padi tahun' q, CAST(tahun AS CHAR) FROM padi_produksi GROUP BY tahun ORDER BY tahun;
SELECT 'lumbung tahun' q, CAST(tahun AS CHAR) FROM lumbung_pangan GROUP BY tahun ORDER BY tahun;
SELECT 'kelompok_tani tahun' q, CAST(tahun AS CHAR) FROM kelompok_tani GROUP BY tahun ORDER BY tahun;
