SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='sispertani' ORDER BY TABLE_NAME, ORDINAL_POSITION;
SELECT '---DISTINCT---' AS x;
SELECT 'lahan_penggunaan.kategori' AS t, kategori AS v FROM lahan_penggunaan GROUP BY kategori;
SELECT 'pasar.jenis' AS t, jenis AS v FROM pasar GROUP BY jenis;
SELECT 'inflasi.wilayah' AS t, wilayah AS v FROM inflasi GROUP BY wilayah;
SELECT 'ternak_populasi' AS t, CONCAT(kelompok,'=',jenis) AS v FROM ternak_populasi GROUP BY kelompok, jenis;
SELECT 'ternak_flow' AS t, CONCAT(arah,'=',jenis) AS v FROM ternak_flow GROUP BY arah, jenis;
SELECT 'ternak_daging_unggas' AS t, jenis AS v FROM ternak_daging WHERE kelompok='unggas' GROUP BY jenis;
SELECT 'ternak_pemotongan_luar_rph' AS t, jenis AS v FROM ternak_pemotongan WHERE lokasi='luar_rph' GROUP BY jenis;
SELECT 'ikan_tangkap.alat' AS t, jenis_alat AS v FROM ikan_tangkap GROUP BY jenis_alat;
SELECT 'ikan_budidaya.jenis' AS t, jenis_budidaya AS v FROM ikan_budidaya GROUP BY jenis_budidaya;
SELECT 'ikan_pemeliharaan.tempat' AS t, tempat AS v FROM ikan_pemeliharaan GROUP BY tempat;
SELECT 'ikan_benih.arah' AS t, arah AS v FROM ikan_benih GROUP BY arah;
SELECT 'horti_produksi.sayuran' AS t, komoditas AS v FROM horti_produksi WHERE kelompok='sayuran' GROUP BY komoditas;
SELECT 'horti_produksi.buah' AS t, komoditas AS v FROM horti_produksi WHERE kelompok='buah_tahunan' GROUP BY komoditas;
SELECT 'horti_luas.sayuran' AS t, komoditas AS v FROM horti_luas WHERE kelompok='sayuran' GROUP BY komoditas;
SELECT 'horti_kab.kelompok' AS t, kelompok AS v FROM horti_produksi_kabupaten GROUP BY kelompok;
SELECT 'palawija' AS t, komoditas AS v FROM palawija_produksi GROUP BY komoditas;
SELECT 'perkebunan_areal' AS t, tanaman AS v FROM perkebunan_areal GROUP BY tanaman;
SELECT 'perkebunan_produksi' AS t, tanaman AS v FROM perkebunan_produksi GROUP BY tanaman;
SELECT 'padi.tahun' AS t, CAST(tahun AS CHAR) AS v FROM padi_produksi GROUP BY tahun ORDER BY tahun;
SELECT 'lumbung.tahun' AS t, CAST(tahun AS CHAR) AS v FROM lumbung_pangan GROUP BY tahun ORDER BY tahun;
SELECT 'kelompok_tani.tahun' AS t, CAST(tahun AS CHAR) AS v FROM kelompok_tani GROUP BY tahun ORDER BY tahun;
SELECT 'kth.tahun' AS t, CAST(tahun AS CHAR) AS v FROM kelompok_tani_hutan GROUP BY tahun;
SELECT 'lahan_desa.tahun' AS t, CAST(tahun AS CHAR) AS v FROM lahan_desa GROUP BY tahun ORDER BY tahun;
SELECT 'kecamatan' AS t, nama AS v FROM kecamatan ORDER BY id;
