SELECT 'kecamatan' AS t, CAST(id AS CHAR) AS k, nama AS v FROM kecamatan ORDER BY id;
SELECT 'lahan_penggunaan.kategori' AS t, '' AS k, kategori AS v FROM lahan_penggunaan GROUP BY kategori;
SELECT 'lahan_penggunaan.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM lahan_penggunaan GROUP BY tahun ORDER BY tahun;
SELECT 'pasar.jenis' AS t, '' AS k, jenis AS v FROM pasar GROUP BY jenis;
SELECT 'inflasi.wilayah' AS t, '' AS k, wilayah AS v FROM inflasi GROUP BY wilayah;
SELECT 'ternak_populasi' AS t, kelompok AS k, jenis AS v FROM ternak_populasi GROUP BY kelompok, jenis;
SELECT 'ternak_flow' AS t, arah AS k, jenis AS v FROM ternak_flow GROUP BY arah, jenis;
SELECT 'ternak_daging' AS t, kelompok AS k, jenis AS v FROM ternak_daging GROUP BY kelompok, jenis;
SELECT 'ternak_pemotongan' AS t, lokasi AS k, jenis AS v FROM ternak_pemotongan GROUP BY lokasi, jenis;
SELECT 'ikan_tangkap.jenis_alat' AS t, '' AS k, jenis_alat AS v FROM ikan_tangkap GROUP BY jenis_alat;
SELECT 'ikan_budidaya.jenis' AS t, '' AS k, jenis_budidaya AS v FROM ikan_budidaya GROUP BY jenis_budidaya;
SELECT 'ikan_pemeliharaan.tempat' AS t, '' AS k, tempat AS v FROM ikan_pemeliharaan GROUP BY tempat;
SELECT 'ikan_benih.arah' AS t, '' AS k, arah AS v FROM ikan_benih GROUP BY arah;
SELECT 'ikan_obyek' AS t, obyek AS k, arah AS v FROM ikan_obyek_penangkapan GROUP BY obyek, arah;
SELECT 'horti_produksi' AS t, kelompok AS k, komoditas AS v FROM horti_produksi GROUP BY kelompok, komoditas;
SELECT 'horti_luas' AS t, kelompok AS k, komoditas AS v FROM horti_luas GROUP BY kelompok, komoditas;
SELECT 'horti_prod_kab' AS t, kelompok AS k, komoditas AS v FROM horti_produksi_kabupaten GROUP BY kelompok, komoditas;
SELECT 'palawija' AS t, '' AS k, komoditas AS v FROM palawija_produksi GROUP BY komoditas;
SELECT 'perkebunan_areal' AS t, '' AS k, tanaman AS v FROM perkebunan_areal GROUP BY tanaman;
SELECT 'perkebunan_produksi' AS t, '' AS k, tanaman AS v FROM perkebunan_produksi GROUP BY tanaman;
SELECT 'padi.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM padi_produksi GROUP BY tahun ORDER BY tahun;
SELECT 'lumbung.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM lumbung_pangan GROUP BY tahun ORDER BY tahun;
SELECT 'kelompok_tani.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM kelompok_tani GROUP BY tahun ORDER BY tahun;
SELECT 'kth.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM kelompok_tani_hutan GROUP BY tahun;
SELECT 'lahan_desa.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM lahan_desa GROUP BY tahun ORDER BY tahun;
SELECT 'pasar.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM pasar GROUP BY tahun ORDER BY tahun;
SELECT 'inflasi.tahun' AS t, '' AS k, CAST(tahun AS CHAR) AS v FROM inflasi GROUP BY tahun ORDER BY tahun;
SELECT 'rowcount' AS t, 'kelompok_tani' AS k, CAST(COUNT(*) AS CHAR) AS v FROM kelompok_tani;
SELECT 'rowcount' AS t, 'kelompok_tani_hutan' AS k, CAST(COUNT(*) AS CHAR) AS v FROM kelompok_tani_hutan;
SELECT 'rowcount' AS t, 'kth_detail' AS k, CAST(COUNT(*) AS CHAR) AS v FROM kth_detail;
SELECT 'rowcount' AS t, 'st2023_desa' AS k, CAST(COUNT(*) AS CHAR) AS v FROM st2023_desa;
SELECT 'rowcount' AS t, 'desa' AS k, CAST(COUNT(*) AS CHAR) AS v FROM desa;
SELECT 'rowcount' AS t, 'lahan_desa' AS k, CAST(COUNT(*) AS CHAR) AS v FROM lahan_desa;
