SELECT '=== TABEL & KOLOM ===' AS x;
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='sispertani' ORDER BY TABLE_NAME, ORDINAL_POSITION;
SELECT '=== DISTINCT PENTING ===' AS x;
SELECT 'kecamatan' t, id, nama AS v FROM kecamatan ORDER BY id;
SELECT 'lahan_penggunaan.kategori' t, NULL, kategori FROM lahan_penggunaan GROUP BY kategori;
SELECT 'lahan_penggunaan.tahun' t, NULL, CAST(tahun AS CHAR) FROM lahan_penggunaan GROUP BY tahun ORDER BY tahun;
SELECT 'pasar.jenis' t, NULL, jenis FROM pasar GROUP BY jenis;
SELECT 'inflasi.wilayah' t, NULL, wilayah FROM inflasi GROUP BY wilayah;
SELECT 'ternak_populasi' t, NULL, CONCAT(kelompok,'=',jenis) FROM ternak_populasi GROUP BY kelompok, jenis ORDER BY kelompok, jenis;
SELECT 'ternak_flow' t, NULL, CONCAT(arah,'=',jenis) FROM ternak_flow GROUP BY arah, jenis ORDER BY arah, jenis;
SELECT 'ternak_daging' t, NULL, CONCAT(kelompok,'=',jenis) FROM ternak_daging GROUP BY kelompok, jenis;
SELECT 'ternak_pemotongan' t, NULL, CONCAT(lokasi,'=',jenis) FROM ternak_pemotongan GROUP BY lokasi, jenis;
SELECT 'ikan_tangkap.jenis_alat' t, NULL, jenis_alat FROM ikan_tangkap GROUP BY jenis_alat;
SELECT 'ikan_budidaya.jenis' t, NULL, jenis_budidaya FROM ikan_budidaya GROUP BY jenis_budidaya;
SELECT 'ikan_pemeliharaan.tempat' t, NULL, tempat FROM ikan_pemeliharaan GROUP BY tempat;
SELECT 'ikan_benih.arah' t, NULL, arah FROM ikan_benih GROUP BY arah;
SELECT 'horti_produksi' t, NULL, CONCAT(kelompok,'=',komoditas) FROM horti_produksi GROUP BY kelompok, komoditas ORDER BY kelompok, komoditas;
SELECT 'horti_luas' t, NULL, CONCAT(kelompok,'=',komoditas) FROM horti_luas GROUP BY kelompok, komoditas ORDER BY kelompok, komoditas;
SELECT 'horti_prod_kab' t, NULL, CONCAT(kelompok,'=',komoditas) FROM horti_produksi_kabupaten GROUP BY kelompok, komoditas ORDER BY kelompok, komoditas;
SELECT 'palawija' t, NULL, komoditas FROM palawija_produksi GROUP BY komoditas;
SELECT 'perkebunan_areal' t, NULL, tanaman FROM perkebunan_areal GROUP BY tanaman;
SELECT 'perkebunan_produksi' t, NULL, tanaman FROM perkebunan_produksi GROUP BY tanaman;
SELECT 'padi.tahun' t, NULL, CAST(tahun AS CHAR) FROM padi_produksi GROUP BY tahun ORDER BY tahun;
SELECT 'lumbung.tahun' t, NULL, CAST(tahun AS CHAR) FROM lumbung_pangan GROUP BY tahun ORDER BY tahun;
SELECT 'kelompok_tani.tahun' t, NULL, CAST(tahun AS CHAR) FROM kelompok_tani GROUP BY tahun ORDER BY tahun;
SELECT 'kth.tahun' t, NULL, CAST(tahun AS CHAR) FROM kelompok_tani_hutan GROUP BY tahun;
SELECT 'lahan_desa.tahun' t, NULL, CAST(tahun AS CHAR) FROM lahan_desa GROUP BY tahun;
SELECT 'pasar.tahun' t, NULL, CAST(tahun AS CHAR) FROM pasar GROUP BY tahun ORDER BY tahun;
SELECT 'inflasi.tahun' t, NULL, CAST(tahun AS CHAR) FROM inflasi GROUP BY tahun ORDER BY tahun;
